### PR TITLE
Branch upc 52

### PR DESCRIPTION
**Pull request by erichirlemann**

### CODE REVIEW

**Comment by SonarTech** [comment]
SonarQube analysis reported 12 new issues:
* 12 major

Details:
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)
* Add a message to this assertion. (org.codehaus.sonar:sonar-update-center-common:src/test/java/org/sonar/updatecenter/common/PluginTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2698)

**Comment by erichirlemann** [comment]
The new issues on dory are newly activated rule on JUnit. I get told this is experimental and will be deactivated.

**Comment by henryju** [comment]
LGTM

**Comment by henryju** [comment]
Again don't forget to merge your commits for cleaner history

**Pull request merged**
